### ISSUE TITLE
I want to help!

### ISSUE THREAD

**Issue by hopeseekr** [peter279k/web-youtube-downloader#1]
If you create issues on this project, I'll attempt to get to them in my limited spare time!

I have created https://www.ourtube.me/ YouTube archiving service and I'm currently calling `youtube-dl` to accomplish archiving.

**Comment by peter279k** [comment]
Thanks for your reply and issue!

This project is for my family members to download YouTube videos easily/conveniently.

After looking at your link, it seems that it's about a self-hosted YouTube video website.

I think it is very different from my website 😃😃.

But it looks great for your OurTube.

If halving any issues about your OurTube website, please feel free to create issue on that repository.

**Comment by peter279k** [comment]
@hopeseekr, just notice that I've published the [youtube-downloader-standalone](https://github.com/peter279k/youtube-downloader-standalone) where it's the Phar building for the [Athlon1600/youtube-downloader](https://github.com/Athlon1600/youtube-downloader).

If you're interested in replace existed `./build.sh` script approach about using `Athlon1600/youtube-downloader` with above standalone Phar building file, you can submit PR to do that :).
